---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# (setup)  specific tasks
- include: "RedHat/setup.yml"
  when: ansible_os_family == 'RedHat'

# (setup)  specific tasks
- include: "Debian/setup.yml"
  when: ansible_os_family == 'Debian'
