---

- name: install zsh packages
  become: yes
  apt: pkg={{ item }} state=installed
  tags: [packages]
  with_items:
    - build-essential
    - zsh
    - git
    - curl

- name: Set zsh as default shell
  become: yes
  user: name=vagrant shell=/usr/bin/zsh

# ============ peco ===========
- include: peco.yml
# ============ zplug ===========
- include: zplug.yml

- name: set template .zsh file to vagrant home
  template: src=zshrc.j2 dest=~vagrant/.zshrc owner=vagrant group=vagrant mode="u=rw,g=r,o=r"
#
# - name: source ~/.zshrc
#   shell: source ~/.zshrc
#   become: no
#
