---
- name: Tap external Homebrew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_repositories
  when: homebrew_repositories

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install/Upgrade Homebrew packages
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: "{{ homebrew_packages }}"
  when: "{{ homebrew_packages }}"


- name: Set zsh as default shell
  become: yes
  user: name={{ user.name }} shell=/usr/local/bin/zsh

- name: Set up zsh as default shell
  shell: /usr/bin/chsh -s '/usr/local/bin/zsh' {{ ansible_env.USER }}
  become: yes

