---
- name: Install zsh packages
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - "@Development tools"
    - zsh
    - git
    - curl

- name: Set zsh as default shell
  become: yes
  user: name={{ user.name }} shell=/usr/bin/zsh
  when: "{{ user.name }}"

# ============ peco ============
- import_tasks: "RedHat/peco.yml"

# ============ zplug ============
- import_tasks: "RedHat/zplug.yml"

- name: Set template .zsh file to vagrant home
  become: no
  template: src=RedHat/zshrc.j2 dest=~/.zshrc name={{ user.name }} group={{ user.name }} mode="u=rw,g=r,o=r"
