---
- name: Install zsh packages
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - "@Development tools"
    - zsh
    - git
    - curl
    - wget
    - nmap
    - nc

- name: Set zsh as default shell
  become: yes
  user: name={{ user.name | default(ansible_env.SUDO_USER) }} shell=/usr/bin/zsh

# ============ peco ============
- import_tasks: "RedHat/peco.yml"

# ============ zplug ============
- import_tasks: "RedHat/zplug.yml"

- name: Set template .zsh file to vagrant home
  become: yes
  become_user: "{{ user.name | default(ansible_env.USER) }}"
  template: src=RedHat/zshrc.j2 dest=~/.zshrc mode="u=rw,g=r,o=r"
