---
- name: Download zplug
  become: yes
  become_user: "{{ user.name }}"
  get_url: url=https://raw.githubusercontent.com/zplug/installer/master/installer.zsh dest=/tmp/zplug.sh
  register: download_zplug

- name: Install zplug
  become: yes
  become_user: "{{ user.name }}"
  shell: zsh /tmp/zplug.sh
  when: download_zplug.changed
